### ISSUE TITLE
SyntaxError: Unexpected token 'E', "Error: abo"... is not valid JSON

### ISSUE THREAD

**Issue by kangfenmao** [kangfenmao/cherry-studio#1]
```log
✓ built in 7.32s
  • electron-builder  version=24.13.3 os=23.5.0
  • loaded configuration  file=/Users/wangqian/Code/github/cherry-studio/electron-builder.yml
  • writing effective config  file=dist/builder-effective-config.yaml
  • skipped dependencies rebuild  reason=npmRebuild is set to false
  • packaging       platform=darwin arch=arm64 electron=28.3.1 appOutDir=dist/mac-arm64
  • signing         file=dist/mac-arm64/Cherry Studio.app platform=darwin type=distribution identity=00093847CDF7DB7FE9CB9A70059BD9905BA8BD7B provisioningProfile=none
  • skipped macOS notarization  reason=`notarize` options were set explicitly `false`
  ⨯ Unexpected token 'E', "Error: abo"... is not valid JSON  failedTask=build stackTrace=SyntaxError: Unexpected token 'E', "Error: abo"... is not valid JSON
    at JSON.parse (<anonymous>)
    at /Users/wangqian/Code/github/cherry-studio/node_modules/@electron/notarize/src/notarytool.ts:79:25
    at Generator.next (<anonymous>)
    at fulfilled (/Users/wangqian/Code/github/cherry-studio/node_modules/@electron/notarize/lib/notarytool.js:28:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

Ref: https://github.com/electron-userland/electron-builder/issues/8259

Ref: https://github.com/electron-userland/electron-builder/issues/8258

**Comment by kangfenmao** [comment]
Fixed: package.json

```json
"resolutions": {
  "@electron/notarize": "2.3.2"
}
```
