### ISSUE TITLE
[错误]: 打开话题白屏了

### ISSUE THREAD

**Issue by proton9091** [kangfenmao/cherry-studio#462]
### 平台

Windows

### 版本

0.8.25

### 错误描述

打开这个话题直接白屏，没反应了
![image](https://github.com/user-attachments/assets/df61b836-f2d6-4173-bae9-f42cccaa4af0)
白屏：

![image](https://github.com/user-attachments/assets/8d7ccfd1-d9d4-45e5-9267-61d9b3bc15c2)

### 重现步骤

打开这个话题
![image](https://github.com/user-attachments/assets/df61b836-f2d6-4173-bae9-f42cccaa4af0)

### 预期行为

正常打开话题

### 相关日志输出

```shell
68index-DzDVxZk7.js:197623 Loaded language: text
index-DzDVxZk7.js:4107 TypeError: Cannot read properties of undefined (reading 'id')
    at isWebSearchModel (index-DzDVxZk7.js:98724:20)
    at Inputbar (index-DzDVxZk7.js:227458:11)
    at Nh (index-DzDVxZk7.js:3586:8)
    at cj (index-DzDVxZk7.js:4240:8)
    at Vk (index-DzDVxZk7.js:6566:96)
    at Uk (index-DzDVxZk7.js:6223:12)
    at Tk (index-DzDVxZk7.js:6217:26)
    at Ik (index-DzDVxZk7.js:6202:7)
    at Nk (index-DzDVxZk7.js:5933:8)
    at Ek (index-DzDVxZk7.js:5987:32)
Li @ index-DzDVxZk7.js:4107
index-DzDVxZk7.js:2901 Uncaught TypeError: Cannot read properties of undefined (reading 'id')
    at isWebSearchModel (index-DzDVxZk7.js:98724:20)
    at Inputbar (index-DzDVxZk7.js:227458:11)
    at Nh (index-DzDVxZk7.js:3586:8)
    at cj (index-DzDVxZk7.js:4240:8)
    at Vk (index-DzDVxZk7.js:6566:96)
    at Uk (index-DzDVxZk7.js:6223:12)
    at Tk (index-DzDVxZk7.js:6217:26)
    at Ik (index-DzDVxZk7.js:6202:7)
    at Nk (index-DzDVxZk7.js:5933:8)
    at Ek (index-DzDVxZk7.js:5987:32)
```

**Comment by kangfenmao** [comment]
设置-模型-选择一下默认模型

**Comment by kangfenmao** [comment]
先下载旧版本使用吧

**Comment by kangfenmao** [comment]
升级到新本版本就没有这个问题了
